### ISSUE TITLE
security breach

### ISSUE THREAD

**Issue by mbarnes-sb** [fl4re/search_parser#6]
https://github.com/fl4re/search_parser/blob/ca6fc579905ac114bf15b4da0aeb10cad63cea04/publish_patch_version.sh#L3
https://github.com/fl4re/search_parser/blob/ca6fc579905ac114bf15b4da0aeb10cad63cea04/publish_patch_version.sh#L4
https://github.com/fl4re/search_parser/blob/ca6fc579905ac114bf15b4da0aeb10cad63cea04/publish_patch_version.sh#L17

**Comment by maxime-helen-sb** [comment]
I removed publish script.
